name: bitlearn_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  http: ^1.2.2
  chewie: ^1.9.0
  video_player: ^2.9.2
  connectivity_plus: ^6.1.1
  geolocator: ^13.0.2
  async: ^2.11.0
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/images/
  # Si tienes más imágenes o quieres incluir toda la carpeta "images":
  # - assets/images/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
